{% set name = "opentelemetry-instrumentation-lancedb" %}
{% set version = "0.57.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: c7ca50aca8133caa250107e4c4115f119d7a6f6da36b83b5ac8b4d21cbabbfed

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - opentelemetry-api >=1.38.0,<2.0.0
    - opentelemetry-instrumentation >=0.59b0
    - opentelemetry-semantic-conventions >=0.59b0
    - opentelemetry-semantic-conventions-ai >=0.5.1,<0.6.0

test:
  source_files:
    - tests
    - pyproject.toml
  imports:
    - opentelemetry.instrumentation.lancedb
  commands:
    - pip check
    - pytest -vvv
  requires:
    - pip
    - pytest
    - pandas
    - lancedb

about:
  home: https://www.traceloop.com/openllmetry
  summary: OpenTelemetry Lancedb instrumentation
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: This library allows tracing client-side calls to LanceDB sent with the official LanceDB library.
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction

extra:
  recipe-maintainers:
    - timkpaine
  skip-lints:
    - invalid_url